### ISSUE TITLE
Can I import bitcoin wallet with a private key?

### ISSUE THREAD

**Issue by ghost** [ArchieR7/BlockChainKit#2]

**Comment by ArchieR7** [comment]
This project provides functions to create a raw transaction for bitcoin, and create private keys with mnemonic.
You can create a class named Wallet to store all of information like private key and mnemonic by yourself.
And this project even can call the function to get bitcoin address from private key, please check `README.md`, then if you have any question, please let me know.

Maybe you can find me well in [Twitter](https://twitter.com/ChangArchie)
